name: GitHub CI Single Action MATLAB Pipeline
on:
  workflow_dispatch:
    branches:
      - main
env:
  MLM_LICENSE_TOKEN: ${{ secrets.MyToken }}

jobs:
  PAdvExample:
    runs-on:   ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
            products: >
                MATLAB
                CI/CD_Automation_for_Simulink_Check
                Embedded_Coder
                Requirements_Toolbox
                Simulink
                Simulink_Check
                Simulink_Coder
                Simulink_Coverage
                Simulink_Report_Generator
                Simulink_Test
          
      - name: run process action
        uses: matlab-actions/run-command@v2
        with:
            command: openProject(pwd);runprocess(Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);