name: GitHub CI Single Action MATLAB Pipeline
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  PAdvExample:
    runs-on:   ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
          
      - name: run process action
        uses: matlab-actions/run-command@v2
        with:
            command: openProject(pwd);runprocess(Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = true);